name: team_c
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_links: ^6.1.4
  auto_size_text: 3.0.0
  cached_network_image: ^3.4.0
  camera: ^0.11.0+1
  collection: 1.18.0
  equatable: 2.0.5
  
  data_table_2: ^2.5.15
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.4.0
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  functions_client: ^2.3.1
  go_router: ^14.2.2
  google_fonts: ^6.2.1
  gotrue: ^2.8.3
  hive: 2.2.3
  http: 1.2.0
  http_parser: ^4.0.0
  intl: 0.19.0
  json_path: ^0.7.4
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: ^2.1.4
  path_provider_android: ^2.2.9
  path_provider_foundation: ^2.4.0
  path_provider_platform_interface: ^2.1.2
  postgrest: ^2.1.3
  provider: ^6.1.2
  realtime_client: ^2.2.0
  shared_preferences: ^2.2.3
  shared_preferences_android: ^2.3.0
  shared_preferences_foundation: ^2.5.0
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences_web: ^2.2.2
  sign_in_with_apple: ^6.1.1
  sign_in_with_apple_platform_interface: ^1.1.0
  sign_in_with_apple_web: ^2.1.0
  sqflite: ^2.3.3+1
  storage_client: ^2.0.2
  supabase: ^2.2.7
  supabase_flutter: ^2.5.11
  timeago: ^3.7.0
  url_launcher: ^6.3.0
  url_launcher_android: ^6.3.8
  url_launcher_ios: ^6.3.1
  url_launcher_platform_interface: 2.3.2
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.6
  webview_flutter_platform_interface: 2.10.0
  webview_flutter_wkwebview: ^3.14.0
  get: ^4.6.6
  fluttertoast: ^8.2.4
  flutter_tts: ^4.0.2
  qr_flutter: ^4.1.0
  file_manager: ^1.0.2
  open_file: ^3.2.1
  
  
 

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  iconsax: ^0.0.8
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.26
  share_plus: ^7.2.2
  permission_handler: ^11.3.1
  contacts_service: ^0.6.3
  get_storage: ^2.1.1
  share: ^2.0.4
  device_info_plus: 9.1.2
  flutter_share: ^2.0.0
dependency_overrides:
  http: 1.2.0
  rxdart: 0.27.7
  uuid: ^4.0.0

dev_dependencies:
  flutter_lints: ^4.0.0
  lints: ^4.0.0

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/images/visitingCard1.jpg
    - assets/images/Presentation3.jpg
    - assets/images/UpdatePassword.png

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

