# Generated by Django 5.0.6 on 2024-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertable',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='chk_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='timeShortageExceed',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='total_hours',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
