# Generated by Django 5.0.6 on 2024-07-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_mastertable_check_in_mastertable_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='passport_withdrawal_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
